server:
  port: 8888
  servlet:
    context-path: /motang
spring:
  application:
    name: motangge


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.132.105.134:3306/book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true

logging:
  level:
    com.motang.motangge: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.motang.motangge.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false